<a href="https://colab.research.google.com/github/emersondivB0/PyProjects/blob/main/DataScience/4_Inmuebles_Residenciales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Report Analysis III

In [2]:
import pandas as pd

In [3]:
datos = pd.read_csv('alquiler.csv', sep = ';')
datos

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0
1,Casa,Lurigancho,2,0,1,100,7000.0,NaN,NaN
2,Local comercial,Ate,0,4,0,150,5200.0,4020.0,1111.0
3,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0
4,Departamento,Ate,1,0,0,48,800.0,230.0,NaN
...,...,...,...,...,...,...,...,...,...
32955,Habitación,Pachacámac,0,0,0,27,800.0,350.0,25.0
32956,Departamento,Lince,3,1,2,78,1800.0,800.0,40.0
32957,Departamento,Rímac,2,1,0,48,1400.0,509.0,37.0
32958,Departamento,Rímac,2,0,0,70,3000.0,760.0,NaN
32959,Local comercial,Pachacámac,0,0,0,250,6500.0,4206.0,1109.0

In [4]:
datos.head(10)

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0
1,Casa,Lurigancho,2,0,1,100,7000.0,NaN,NaN
2,Local comercial,Ate,0,4,0,150,5200.0,4020.0,1111.0
3,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0
4,Departamento,Ate,1,0,0,48,800.0,230.0,NaN
5,Departamento,Barranco,3,1,0,70,1200.0,NaN,NaN
6,Departamento,Comas,2,0,0,50,1300.0,301.0,17.0
7,Casa en condominio,Ate,5,4,5,750,22000.0,NaN,NaN
8,Casa en condominio,El Agustino,2,2,0,65,1000.0,NaN,NaN
9,Local comercial,Pachacámac,0,3,0,695,35000.0,19193.0,3030.0

Debemos filtrar los inmuebles residenciales solamente

In [5]:
list(datos['Tipo'].drop_duplicates())

['Habitación',
 'Casa',
 'Local comercial',
 'Departamento',
 'Casa en condominio',
 'Edificio completo',
 'Flat',
 'Tienda/Salón',
 'Almacén',
 'Casa comercial',
 'Casa de villa',
 'Terreno',
 'Cochera',
 'Loft',
 'Tienda en Centro Comercial',
 'Chacra',
 'Terreno em condominio',
 'Oficina',
 'Chalet',
 'Studio',
 'Hotel',
 'Local industrial']

In [6]:
residencial = ['Habitación',
 'Casa',
 'Departamento',
 'Casa en condominio',
 'Casa comercial',
 'Casa de villa']
residencial

['Habitación',
 'Casa',
 'Departamento',
 'Casa en condominio',
 'Casa comercial',
 'Casa de villa']

Con esa lista, filtramos los datos que queremos

In [7]:
seleccion = datos['Tipo'].isin(residencial)
seleccion

0         True
1         True
2        False
3         True
4         True
         ...
32955     True
32956     True
32957     True
32958     True
32959    False
Name: Tipo, Length: 32960, dtype: bool

In [8]:
datos_residencial = datos[seleccion]
datos_residencial

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0
1,Casa,Lurigancho,2,0,1,100,7000.0,NaN,NaN
3,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0
4,Departamento,Ate,1,0,0,48,800.0,230.0,NaN
5,Departamento,Barranco,3,1,0,70,1200.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
32953,Departamento,Santa Anita,2,0,0,70,900.0,490.0,48.0
32955,Habitación,Pachacámac,0,0,0,27,800.0,350.0,25.0
32956,Departamento,Lince,3,1,2,78,1800.0,800.0,40.0
32957,Departamento,Rímac,2,1,0,48,1400.0,509.0,37.0
32958,Departamento,Rímac,2,0,0,70,3000.0,760.0,NaN

In [9]:
list(datos_residencial['Tipo'].drop_duplicates())

['Habitación',
 'Casa',
 'Departamento',
 'Casa en condominio',
 'Casa comercial',
 'Casa de villa']

Los índices quedan según el dataframe original, hay que ordenarlos en secuencia

In [10]:
datos_residencial.shape[0]

22845

In [11]:
datos_residencial.index = range(datos_residencial.shape[0])
datos_residencial

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0
1,Casa,Lurigancho,2,0,1,100,7000.0,NaN,NaN
2,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0
3,Departamento,Ate,1,0,0,48,800.0,230.0,NaN
4,Departamento,Barranco,3,1,0,70,1200.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
22840,Departamento,Santa Anita,2,0,0,70,900.0,490.0,48.0
22841,Habitación,Pachacámac,0,0,0,27,800.0,350.0,25.0
22842,Departamento,Lince,3,1,2,78,1800.0,800.0,40.0
22843,Departamento,Rímac,2,1,0,48,1400.0,509.0,37.0
22844,Departamento,Rímac,2,0,0,70,3000.0,760.0,NaN

In [12]:
# prueba:

numeros = [i for i in range(11)]
letras = [chr(i + 65) for i in range(11)]
nome_coluna = ['N']

df = pd.DataFrame(data = numeros, index = letras, columns = nome_coluna)

In [13]:
seleccion= df['N'].isin([i for i in range(11) if i % 2 == 0])
df = df[seleccion]
df

    N
A   0
C   2
E   4
G   6
I   8
K  10

## Exporting Database

In [14]:
datos_residencial.to_csv('alquiler_residencial.csv', sep = ';')

In [15]:
datos_residencial_2 = pd.read_csv('alquiler_residencial.csv', sep = ';')
datos_residencial_2

,Unnamed: 0,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0
1,1,Casa,Lurigancho,2,0,1,100,7000.0,NaN,NaN
2,2,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0
3,3,Departamento,Ate,1,0,0,48,800.0,230.0,NaN
4,4,Departamento,Barranco,3,1,0,70,1200.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
22840,22840,Departamento,Santa Anita,2,0,0,70,900.0,490.0,48.0
22841,22841,Habitación,Pachacámac,0,0,0,27,800.0,350.0,25.0
22842,22842,Departamento,Lince,3,1,2,78,1800.0,800.0,40.0
22843,22843,Departamento,Rímac,2,1,0,48,1400.0,509.0,37.0
22844,22844,Departamento,Rímac,2,0,0,70,3000.0,760.0,NaN

In [16]:
# cuando se exporta, por defecto, se añaden índices extra, como mi dataset ya tiene, hay que eliminarlos
datos_residencial.to_csv('alquiler_residencial.csv', sep = ';', index = False)

In [17]:
datos_residencial_2 = pd.read_csv('alquiler_residencial.csv', sep = ';')
datos_residencial_2

,Tipo,Distrito,Cuartos,Vacantes,Suites,Area,Valor,Mantenimiento,Impuesto
0,Habitación,San Borja,1,0,0,40,1700.0,500.0,60.0
1,Casa,Lurigancho,2,0,1,100,7000.0,NaN,NaN
2,Departamento,Pachacámac,1,0,0,15,800.0,390.0,20.0
3,Departamento,Ate,1,0,0,48,800.0,230.0,NaN
4,Departamento,Barranco,3,1,0,70,1200.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
22840,Departamento,Santa Anita,2,0,0,70,900.0,490.0,48.0
22841,Habitación,Pachacámac,0,0,0,27,800.0,350.0,25.0
22842,Departamento,Lince,3,1,2,78,1800.0,800.0,40.0
22843,Departamento,Rímac,2,1,0,48,1400.0,509.0,37.0
22844,Departamento,Rímac,2,0,0,70,3000.0,760.0,NaN